name: fly_todo
description: "A simple TODO app made with flutter."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.7.2

dependencies:
    dynamic_color: ^1.7.0
    flutter:
        sdk: flutter
    http: ^1.3.0
    shared_preferences: ^2.5.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
