name: fly_todo
description: "A simple cross-platform material design TODO app made with Flutter."
publish_to: "none"
version: 0.9.0

environment:
    sdk: ^3.7.2

dependencies:
    build_runner: ^2.4.15
    dynamic_color: ^1.7.0
    flutter:
        sdk: flutter
    http: ^1.3.0
    shared_preferences: ^2.5.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    msix: ^3.16.8

msix_config:
    display_name: Fly TODO
    publisher_display_name: Ilian Delagrange
    identity_name: IlianDelagrange.FlyTODO
    family_name: IlianDelagrange.FlyTODO_e59jqyr24yf08
    msix_version: 0.9.0.0
    logo_path: web/icons/web-app-manifest-512x512.png
    capabilities: internetClient
    architecture: x64
    publisher: CN=FBE2EC37-2851-4624-9F60-D21F9C6C6665
    store: true

flutter:
    uses-material-design: true
