// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfx53UTjNFsOR0n3mL7hDAJNh15FZ_zHY',
    appId: '1:252245842703:web:a14c2f757e787f5552fc7a',
    messagingSenderId: '252245842703',
    projectId: 'fly-todo',
    authDomain: 'fly-todo.firebaseapp.com',
    storageBucket: 'fly-todo.firebasestorage.app',
    measurementId: 'G-1SHZM4ZTJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO_I2t82c8tMbHsU5cWMW1ChR1r1alLnk',
    appId: '1:252245842703:android:10dcf712f83d605452fc7a',
    messagingSenderId: '252245842703',
    projectId: 'fly-todo',
    storageBucket: 'fly-todo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfx53UTjNFsOR0n3mL7hDAJNh15FZ_zHY',
    appId: '1:252245842703:web:dc6f43ccab1949e152fc7a',
    messagingSenderId: '252245842703',
    projectId: 'fly-todo',
    authDomain: 'fly-todo.firebaseapp.com',
    storageBucket: 'fly-todo.firebasestorage.app',
    measurementId: 'G-2N49TPTDNP',
  );
}
