on:
    push:
        branches:
            - prod
env:
    TARGET_APK_NAME: fly-todo-release

name: Build Android APK
jobs:
    android-release-build:
        name: android-release-build
        runs-on: ubuntu-latest
        container: ghcr.io/niklaslehnfeld/flutter-essentials-docker:master
        steps:
            - uses: actions/checkout@v4
            - uses: NiklasLehnfeld/flutter-android-build-action@v1
              id: android-build
              with:
                  release: false
                  #   keystore: ${{ secrets.KEYSTORE }}
                  #   keystore-pwd: "${{ secrets.KEYSTORE_PASSWORD }}"
                  #   key-pwd: "${{ secrets.KEY_PASSWORD }}"

            - run: mv {{ steps.android-build.outputs.apk-path }} ./${{env.TARGET_APK_NAME}}.apk
            - name: Archive APK
              uses: actions/upload-artifact@v4
              with:
                  name: release-apk
                  path: ./${{env.TARGET_APK_NAME}}.apk
            # - name: Archive AAB
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: release-aab
            #       path: ${{ steps.android-build.outputs.aab-path }}
