on:
    push:
        branches:
            - main
        paths:
            - "flutter-client/**"
            - ".github/workflows/**"
    workflow_dispatch:

concurrency:
    group: cancel-on-new-run
    cancel-in-progress: true

env:
    SUB_DIR: flutter-client
    ANDROID_TARGET_BINARY_NAME: android-fly-todo-release
    WINDOWS_TARGET_BUNDLE_NAME: windows-fly-todo-release
    ANDROID_APK_PATH: ./build/app/outputs/flutter-apk/app-release.apk
    WINDOWS_BINARY_LOCATION: build/windows/x64/runner/Release/fly_todo.msix
    STORE_FILE_PATH: /tmp/my-release-key.jks

name: Build the binaries and publish if on Prod
jobs:
    build-android-apk:
        runs-on: ubuntu-latest
        name: Build the Android APK
        steps:
            - uses: actions/checkout@v4

            - name: Set up Java 17
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: 17
                  cache: "gradle"

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true

            - name: Print all Flutter versions
              run: flutter doctor -v

            - name: Set up Keystore
              run: |
                  echo "$KEYSTORE_BASE64" | base64 -d > ${{ env.STORE_FILE_PATH }}
              env:
                  KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

            - name: Set up keystore properties
              run: |
                  echo "storeFile=${{ env.STORE_FILE_PATH }}" >> $GITHUB_ENV
                  echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> $GITHUB_ENV
                  echo "keyAlias=${{ secrets.ALIAS }}" >> $GITHUB_ENV
                  echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

            - name: Get the packages
              working-directory: ${{env.SUB_DIR}}
              run: flutter pub get

            - name: Build APK
              working-directory: ${{env.SUB_DIR}}
              run: flutter build apk --release

            - name: Rename APK
              working-directory: ${{env.SUB_DIR}}
              run: mv ${{env.ANDROID_APK_PATH}} ./${{env.ANDROID_TARGET_BINARY_NAME}}.apk

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: ${{env.ANDROID_TARGET_BINARY_NAME}}
                  path: ./${{env.SUB_DIR}}/${{env.ANDROID_TARGET_BINARY_NAME}}.apk
                  if-no-files-found: error
    build-windows-binary:
        runs-on: windows-latest
        name: Build the Windows installer
        steps:
            - uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true
            - run: flutter --version

            - name: Generate MSIX
              working-directory: ${{env.SUB_DIR}}
              run: dart run msix:create --install-certificate false
            - name: Rename APK
              working-directory: ${{env.SUB_DIR}}
              run: mv ${{env.WINDOWS_BINARY_LOCATION}} ./${{env.WINDOWS_TARGET_BUNDLE_NAME}}.msix

            - name: Upload binary
              uses: actions/upload-artifact@v4
              with:
                  name: ${{env.WINDOWS_TARGET_BUNDLE_NAME}}
                  path: ./${{env.SUB_DIR}}/${{env.WINDOWS_TARGET_BUNDLE_NAME}}.msix
                  if-no-files-found: error
    publish-github-release:
        permissions:
            packages: write
            contents: write
        if: github.event_name == 'workflow_dispatch'
        needs:
            - build-android-apk
        runs-on: ubuntu-latest
        name: Publish the GitHub release
        steps:
            - uses: actions/checkout@v4

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: Extract version
              id: get_version
              run: |
                  version=$(grep -E '^version:' ./flutter-client/pubspec.yaml | sed 's/version:[[:space:]]*//')
                  echo "version=$version"
                  echo "version=$version" >> $GITHUB_OUTPUT

            - name: Create a Release
              uses: ncipollo/release-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag: v${{ steps.get_version.outputs.version }}
                  artifacts: ./artifacts/**/*.apk
                  generateReleaseNotes: true
                  draft: true
    # pushing-microsoft-store:
    #     needs:
    #         - build-windows-binary

    #     if: github.event_name == 'workflow_dispatch'
    #     runs-on: ubuntu-latest
    #     name: Publish version on Microsoft Store
    # TODO : after certification
