on:
    push:
        branches:
            - main
        paths:
            - "flutter-client/**"
            - ".github/workflows/**"
    pull_request:
        branches:
            - prod
        paths:
            - "flutter-client/**"
            - ".github/workflows/**"
env:
    SUB_DIR: flutter-client
    ANDROID_TARGET_BINARY_NAME: android-fly-todo-release
    WINDOWS_TARGET_BUNDLE_NAME: windows-fly-todo-release
    ANDROID_APK_PATH: ./build/app/outputs/flutter-apk/app-release.apk
    WINDOWS_BINARY_LOCATION: build/windows/x64/runner/Release/fly_todo.msix

name: Build the flutter binaries
jobs:
    build-android-apk:
        concurrency:
            group: build
            cancel-in-progress: true

        runs-on: ubuntu-latest
        name: Build the Android APK
        steps:
            - uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true
            - run: flutter --version

            - name: Build APK
              working-directory: ${{env.SUB_DIR}}
              run: flutter build apk --release

            - name: Rename APK
              working-directory: ${{env.SUB_DIR}}
              run: mv ${{env.ANDROID_APK_PATH}} ./${{env.ANDROID_TARGET_BINARY_NAME}}.apk

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: ${{env.ANDROID_TARGET_BINARY_NAME}}
                  path: ./${{env.SUB_DIR}}/${{env.ANDROID_TARGET_BINARY_NAME}}.apk
                  if-no-files-found: error
    build-windows-binary:
        concurrency:
            group: build
            cancel-in-progress: true

        runs-on: windows-latest
        name: Build the Windows installer
        steps:
            - uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true
            - run: flutter --version

            - name: Generate MSIX
              working-directory: ${{env.SUB_DIR}}
              run: dart run msix:create --install-certificate false
            - name: Rename APK
              working-directory: ${{env.SUB_DIR}}
              run: mv ${{env.WINDOWS_BINARY_LOCATION}} ./${{env.ANDROID_TARGET_BINARY_NAME}}.msix

            - name: Upload binary
              uses: actions/upload-artifact@v4
              with:
                  name: ${{env.WINDOWS_TARGET_BUNDLE_NAME}}
                  path: ./${{env.SUB_DIR}}/${{env.ANDROID_TARGET_BINARY_NAME}}.msix
                  if-no-files-found: error
    publish-github-release:
        if: github.ref == 'refs/heads/prod'
        concurrency:
            group: publish
            cancel-in-progress: true
        needs:
            - build-android-apk
            - build-windows-binary
        runs-on: ubuntu-latest
        name: Publish the GitHub release
        steps:
            - uses: actions/checkout@v4

            - name: Download artifacts
              uses: actions/download-artifact@v4

            - run: ls -la
            - run: echo "It would upload the binaries"
